spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/discodeit}
    username: ${DB_USERNAME:discodeit_user}
    password: ${DB_PASSWORD:discodeit1234}
    driver-class-name: org.postgresql.Driver

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

server:
  port: ${PORT:80}

logging:
  level:
    com.sprint.mission.discodeit: info
